server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:

        # for file system config properties
        #native:
        #  search-locations: /home/toshiba/Documents/proyectos/spring/cloud/spmia-chapter2/config-repository-local/license-service/
        git:
          uri: 

